### ISSUE TITLE
fails to build on nginx => 1.9.13 due to new ngx_udp_connection_t

### ISSUE THREAD

**Issue by JoeOrtiz** [fluent/nginx-fluentd-module#10]
Build now fails with new versions of nginx due to the recently added UDP added in 1.9.13

```
../nginx-fluentd-module/ngx_http_fluentd_module.c:62:5: error: unknown type name 'ngx_udp_connection_t'
     ngx_udp_connection_t      *udp_connection;
     ^
../nginx-fluentd-module/ngx_http_fluentd_module.c:81:27: error: unknown type name 'ngx_udp_connection_t'
 ngx_int_t ngx_udp_connect(ngx_udp_connection_t *uc);
                           ^
../nginx-fluentd-module/ngx_http_fluentd_module.c: In function 'ngx_fluentd_init_endpoint':
../nginx-fluentd-module/ngx_http_fluentd_module.c:243:5: error: unknown type name 'ngx_udp_connection_t'
     ngx_udp_connection_t  *uc;
     ^
../nginx-fluentd-module/ngx_http_fluentd_module.c:253:28: error: 'ngx_udp_connection_t' undeclared (first use in this function)
     uc = ngx_calloc(sizeof(ngx_udp_connection_t), cf->log);
                            ^
../nginx-fluentd-module/ngx_http_fluentd_module.c:253:28: note: each undeclared identifier is reported only once for each function it appears in
../nginx-fluentd-module/ngx_http_fluentd_module.c:260:7: error: request for member 'sockaddr' in something not a structure or union
     uc->sockaddr = endpoint->peer_addr.sockaddr;
       ^
../nginx-fluentd-module/ngx_http_fluentd_module.c:261:7: error: request for member 'socklen' in something not a structure or union
     uc->socklen = endpoint->peer_addr.socklen;
       ^
../nginx-fluentd-module/ngx_http_fluentd_module.c:262:7: error: request for member 'server' in something not a structure or union
     uc->server = endpoint->peer_addr.name;
       ^
../nginx-fluentd-module/ngx_http_fluentd_module.c:266:7: error: request for member 'log' in something not a structure or union
     uc->log = cf->cycle->new_log;
       ^
../nginx-fluentd-module/ngx_http_fluentd_module.c:268:7: error: request for member 'log' in something not a structure or union
     uc->log.handler = NULL;
       ^
../nginx-fluentd-module/ngx_http_fluentd_module.c:269:7: error: request for member 'log' in something not a structure or union
     uc->log.data = NULL;
       ^
../nginx-fluentd-module/ngx_http_fluentd_module.c:270:7: error: request for member 'log' in something not a structure or union
     uc->log.action = "logging";
       ^
../nginx-fluentd-module/ngx_http_fluentd_module.c: In function 'ngx_fluentd_cleanup':
../nginx-fluentd-module/ngx_http_fluentd_module.c:286:29: error: request for member 'connection' in something not a structure or union
         if(e->udp_connection->connection) {
                             ^
../nginx-fluentd-module/ngx_http_fluentd_module.c:287:51: error: request for member 'connection' in something not a structure or union
             ngx_close_connection(e->udp_connection->connection);
                                                   ^
../nginx-fluentd-module/ngx_http_fluentd_module.c: In function 'ngx_http_fluentd_send':
../nginx-fluentd-module/ngx_http_fluentd_module.c:302:5: error: unknown type name 'ngx_udp_connection_t'
     ngx_udp_connection_t  *uc;
     ^
../nginx-fluentd-module/ngx_http_fluentd_module.c:306:11: error: request for member 'connection' in something not a structure or union
     if (uc->connection == NULL) {
           ^
../nginx-fluentd-module/ngx_http_fluentd_module.c:307:12: error: implicit declaration of function 'ngx_udp_connect' [-Werror=implicit-function-declaration]
         if(ngx_udp_connect(uc) != NGX_OK) {
            ^
../nginx-fluentd-module/ngx_http_fluentd_module.c:308:18: error: request for member 'connection' in something not a structure or union
             if(uc->connection != NULL) {
                  ^
../nginx-fluentd-module/ngx_http_fluentd_module.c:309:39: error: request for member 'connection' in something not a structure or union
                 ngx_free_connection(uc->connection);
                                       ^
../nginx-fluentd-module/ngx_http_fluentd_module.c:310:19: error: request for member 'connection' in something not a structure or union
                 uc->connection = NULL;
                   ^
../nginx-fluentd-module/ngx_http_fluentd_module.c:316:11: error: request for member 'connection' in something not a structure or union
         uc->connection->data = l;
           ^
../nginx-fluentd-module/ngx_http_fluentd_module.c:317:11: error: request for member 'connection' in something not a structure or union
         uc->connection->read->handler = ngx_http_fluentd_dummy_handler;
           ^
../nginx-fluentd-module/ngx_http_fluentd_module.c:318:11: error: request for member 'connection' in something not a structure or union
         uc->connection->read->resolver = 0;
           ^
../nginx-fluentd-module/ngx_http_fluentd_module.c:321:20: error: request for member 'connection' in something not a structure or union
     n = ngx_send(uc->connection, buf, len);
                    ^
In file included from src/core/ngx_core.h:59:0,
                 from ../nginx-fluentd-module/ngx_http_fluentd_module.c:15:
../nginx-fluentd-module/ngx_http_fluentd_module.c:329:40: error: request for member 'log' in something not a structure or union
         ngx_log_error(NGX_LOG_CRIT, &uc->log, 0, "send() incomplete");
                                        ^
src/core/ngx_log.h:86:10: note: in definition of macro 'ngx_log_error'
     if ((log)->log_level >= level) ngx_log_error_core(level, log, __VA_ARGS__)
          ^
../nginx-fluentd-module/ngx_http_fluentd_module.c:329:40: error: request for member 'log' in something not a structure or union
         ngx_log_error(NGX_LOG_CRIT, &uc->log, 0, "send() incomplete");
                                        ^
src/core/ngx_log.h:86:62: note: in definition of macro 'ngx_log_error'
     if ((log)->log_level >= level) ngx_log_error_core(level, log, __VA_ARGS__)
                                                              ^
cc1: all warnings being treated as errors
make[1]: *** [objs/addon/nginx-fluentd-module/ngx_http_fluentd_module.o] Error 1
objs/Makefile:1640: recipe for target 'objs/addon/nginx-fluentd-module/ngx_http_fluentd_module.o' failed
```
